name: Dev Astronomer CI - Deploy Code

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        mkdir -p /home/runner/.ssh
        ssh-keyscan example.com >> /home/runner/.ssh/known_hosts
        echo "${{ secrets.GH_SSH_KEY }}" >> /home/runner/.ssh/github_actions

        
