name: Dev Astronomer CI - Deploy Code

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning

env:
  ## Sets Deployment API key credentials as environment variables
  GH_SSH_KEY: ${{ secrets.GH_SSH_KEY }}
  GH_KNOWN_HOSTS: ${{ secrets.GH_KNOWN_HOSTS }}
  PUB_KEY: ${{ secrets.PUB_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Deploy to Astro
      run: |
        mkdir /home/runner/.ssh
        echo $GH_SSH_KEY > /home/runner/.ssh/id_rsa
        echo $GH_KNOWN_HOSTS > /home/runner/.ssh/known_hosts
        ssh-keygen -R 140.82.114.3
        apt-get update && apt-get install -y git
        chmod 600 /home/runner/.ssh/id_rsa
        git clone git@github.com:Palta-Data-Platform/paltabrain_dq_services.git
        
