name: Dev Astronomer CI - Deploy Code

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        mkdir .ssh
        echo "${{ secrets.GH_SSH_KEY }}" > .ssh/id_rsa
        echo ${{ secrets.GH_KNOWN_HOSTS }} > .ssh/known_hosts
        apt-get update && apt-get install -y git
        pip install git+ssh://git@github.com/Palta-Data-Platform/paltabrain_dq_services.git
        
